#################################################################################
# Model Optimization Parameters                                                 #
#################################################################################
HYPERPARAMETERS:
  BETA1: 0.9              # exponential decay rate for the first moment estimates 
  BETA2: 0.999            # exponential decay rate for the second moment estimates 
  EPSILON: 10e-8          # exponential decay rate for the first moment estimates 

  LEARNING_RATE: 10e-5    # rate of weight adjustment with respect to the loss gradient

  BATCH_SIZE: 4           # number of training examples per iteration
  EPOCHS: 200             # number of epochs training is running for

  PATIENCE: 10            # used for early stopping, if the loss doesn't
                          # improve after specified epochs it terminates
  BASE_LINE: 2e-4         # training will only stop if the model doesn't
                          # show improvement over the baseline value.

#################################################################################
# Enviroment Configeration                                                      #
#################################################################################
ENVIROMENT_CONFIG:
  SAVE_EVERY: 10          # model is saved every specified epochs

  VERBOSE: 1              # verbosity flag
                          # SILENT: 0, NORMAL:1, DEBUG:2


DECALIBRATIONS:
  ITERATIVE_REFINEMENT: false   # indicate if using the five network approach
  RANGE_DISPLACEMENT: 0.5       # translation decalibration range
  RANGE_ROTATION: 5             # rotation decalibration range

#################################################################################
# Data Description                                                              #
#################################################################################
DATA_INFORMATION:
  # describing the data
  IMAGE_HEIGHT: &IMAGE_HEIGHT 352
  IMAGE_WIDTH: &IMAGE_WIDTH 1216
  IMAGE_SIZE: 
    - *IMAGE_WIDTH
    - *IMAGE_HEIGHT
  DUAL_QUATERNIONS: false

#################################################################################
# Dataset Generation Parameters                                                 #
#################################################################################
DATASET:
  # define how the data is generated
  # NUM_FRAMES: 100         # size of the dataset (toy dataset)
  NUM_FRAMES: 18750     # size of the dataset (original regnet size)
  # NUM_FRAMES: 18750     # size of the dataset (2x original regnet size)

  TRAIN_PCT: 0.8          # percentage of dataset as training dataset
  VALID_PCT: 0.1          # percentage of dataset as validation dataset
  TEST_PCT: 0.1           # percentage of dataset as test dataset
